// Layout for the auth pages
import "@/app/globals.css";
import styles from './auth_layout.module.css'

export const metadata = { // Cambiar //
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
    return (
        <section className="bg-black h-full w-full flex content-center justify-center">
            <div className="bg-slate-300 rounded-md w-fit h-fit">
                {children}
            </div>
        </section>
    )
}
