import React from 'react';
import Image from 'next/image';

import NavBar from '@/components/actuators/bars/NavBar.jsx';

//import "./globals.css";

export const metadata = {
    title: "Dash Board",
    description: "Generated by me",
};
  
export default function DashBoardLayout({ children }){

    return (
        <section className="h-full w-full flex">
            <NavBar position="left" className="w-3/12"> {/* Side Bar */}
                <figure> {/* Hide trigger button */}
                
                </figure>
                <figure className="relative block w-full h-20"> {/* Logo Image */}
                    <Image
                        src="/multimedia/img/qiski-banner.webp"
                        alt="Qiskit Banner"
                        fill 
                        style={{ objectFit: 'contain' }} 
                    />
                </figure>
            </NavBar>
            <section> {/* Main Content */}
                <nav> {/* Top Bar */}
                    <div> {/* Section description */}

                    </div>
                    <div> {/* Search bar */}

                    </div>
                    <div> {/* Action buttons */}
                        
                    </div>
                </nav>
                {children}
            </section>
        </section>
    );
};