import React from 'react';
import 

export const metadata = {
    title: "Dash Board",
    description: "Generated by me",
};
  

export default function DashBoardLayout({ children }){
    return (
        <html lang="en">
            <body>
                <nav className=""> {/* Side Bar */}

                </nav>
                <section> {/* Main Content */}
                    <nav> {/* Top Bar */}
                        <div> {/* Section description */}

                        </div>
                        <div> {/* Search bar */}

                        </div>
                        <div> {/* Action buttons */}
                            
                        </div>
                    </nav>
                    {children}
                </section>
            </body>
        </html>
    );
};